# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

"""Cluster storage contracts and reusable buffers."""

from vllm.v1.spec_decode.retrospec.legacy.store.contracts import (
    RetroSpecClusterBlockMetadata,
    RetroSpecClusterBlockTable,
    RetroSpecCompactResolvedClusterPages,
    RetroSpecCompactTokenRange,
    RetroSpecCompactVerificationResolvedPages,
    RetroSpecFullVerificationDescriptor,
    RetroSpecFullVerificationStaging,
    RetroSpecFullVerificationTicket,
    RetroSpecRankedDraftResolvedClusters,
    RetroSpecResolvedClusterPages,
    RetroSpecStagedClusterInput,
    RetroSpecStagedTokenKV,
    RetroSpecVerificationMissAdmission,
    RetroSpecVerificationResolveRequest,
    _ClusterBlockDescriptor,
    _LayerPrefetchDescriptorArena,
    _SubmittedVerificationResolve,
)
from vllm.v1.spec_decode.retrospec.legacy.store.pool import (
    _CPUPageSlab,
    _FullVerificationGPUArena,
    _FullVerificationSourceSnapshot,
    _LayerClusterPagePool,
    _PinnedPageTransferSlot,
)
from vllm.v1.spec_decode.retrospec.legacy.store.prefetch_types import (
    _PREFETCH_SOURCE_PRIORITY,
    RetroSpecClusterResolveMode,
    RetroSpecResidentPrefetchInput,
    RetroSpecResidentPrefetchSource,
    _DeferredResidentPrefetchWave,
    _PinnedSelectionSlot,
    _PinnedStagingSlot,
    _PinnedVerificationMissSlot,
    _PreparedResidentPrefetchRecord,
    _ResidentPrefetchPriorityExecutor,
    _ResidentPrefetchWaveFuture,
    _ResidentPrefetchWaveProgress,
    _StagedResidentPrefetchRecord,
    _StagedResidentPrefetchWave,
    _VerificationResolveGPUArena,
)
from vllm.v1.spec_decode.retrospec.legacy.store.transfer import (
    _FullVerificationTransferBuffer,
)

__all__ = [
    "RetroSpecClusterResolveMode",
    "RetroSpecResidentPrefetchSource",
    "_PREFETCH_SOURCE_PRIORITY",
    "_PinnedStagingSlot",
    "RetroSpecResidentPrefetchInput",
    "_PinnedSelectionSlot",
    "_PinnedVerificationMissSlot",
    "_VerificationResolveGPUArena",
    "_StagedResidentPrefetchRecord",
    "_ResidentPrefetchWaveProgress",
    "_StagedResidentPrefetchWave",
    "_DeferredResidentPrefetchWave",
    "_ResidentPrefetchPriorityExecutor",
    "_PreparedResidentPrefetchRecord",
    "_ResidentPrefetchWaveFuture",
    "RetroSpecClusterBlockTable",
    "RetroSpecClusterBlockMetadata",
    "RetroSpecStagedTokenKV",
    "RetroSpecStagedClusterInput",
    "_ClusterBlockDescriptor",
    "_LayerPrefetchDescriptorArena",
    "RetroSpecCompactTokenRange",
    "RetroSpecFullVerificationDescriptor",
    "RetroSpecFullVerificationStaging",
    "RetroSpecFullVerificationTicket",
    "RetroSpecResolvedClusterPages",
    "RetroSpecCompactResolvedClusterPages",
    "RetroSpecRankedDraftResolvedClusters",
    "RetroSpecCompactVerificationResolvedPages",
    "RetroSpecVerificationMissAdmission",
    "RetroSpecVerificationResolveRequest",
    "_SubmittedVerificationResolve",
    "_CPUPageSlab",
    "_FullVerificationSourceSnapshot",
    "_PinnedPageTransferSlot",
    "_LayerClusterPagePool",
    "_FullVerificationGPUArena",
    "_FullVerificationTransferBuffer",
]
